### ISSUE TITLE
Improve data location

### ISSUE THREAD

**Issue by remram44** [VIDA-NYU/reference-data-repository#5]
**Describe the bug**
refdata always puts data in `~/.refdata`, however this is not a good location on many OS.

**To Reproduce**
1. Use refdata on Linux: data goes in `/home/remram/.refdata`, but [the FreeDesktop specification says](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) it should be `/home/remram/.cache/refdata` (or somewhere else if `$XDG_CACHE_HOME` is set)
2. Use refdata on Windows: data goes in `C:\Users\remram\.refdata`, but it should be `C:\Documents and Settings\<User>\Application Data\Local Settings\refdata`
3. Use refdata on MacOS: data goes in `/Users/remram/.refdata`, but it should be `/Users/remram/Library/Application Support/refdata`

**Expected behavior**
refdata should put data in the usual location on each operating system, for example using the [`appdirs`](https://github.com/ActiveState/appdirs) library

**Additional context**
Similar to https://github.com/fatiando/pooch/issues/26

**Comment by heikomuller** [comment]
Thank you for pointing out this issue!

I would still like to have the option that allows the user to (explicitly) specify the storage directory. That is, if the environment variable *REFDATA_BASEDIR* is set, downloaded files will be stored in the specified directory. Otherwise, downloaded files will go into the `appdirs.user_cache_dir`.

Would that be a satisfying solution?

**Comment by remram44** [comment]
Yes, definitely! I think this is what Pooch does too.
